language: python

install:
        - wget https://github.com/gohugoio/hugo/releases/download/v0.72.0/hugo_0.72.0_Linux-64bit.deb
        - sudo dpkg -i hugo*.deb
        - pip install Pygments

script:
        - hugo
               
after_success:
       if [ -n "$GITHUB_TOKEN" ]; then
       git checkout --orphan master
       git rm -rf
       mv public/* .
       rm -rf public hugo_*
       git add -f --ignore-errors --all
       git -c user.name='travis' -c user.email='travis' commit -m init
       git push -f -q https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG master
